-- =============================================================================
-- V18__create_billing_accounts_charges_and_runs.sql
-- Manual billing preparation: reusable profiles, tuition charges, allocations
-- and auditable individual/selected/filtered invoice runs.
-- RG 5866 is explicitly not applicable for the first client and no fields from
-- that regime are generated by this schema.
-- =============================================================================

ALTER TABLE payments
    ALTER COLUMN student_id DROP NOT NULL;

ALTER TABLE tuition_ledger_entries
    DROP CONSTRAINT IF EXISTS chk_tuition_ledger_status;

UPDATE tuition_ledger_entries
SET status = CASE status
    WHEN 'MOCK_PENDING' THEN 'PENDING'
    WHEN 'MOCK_PAID' THEN 'PAID'
    ELSE status
END;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'tuition_ledger_entries'
          AND column_name = 'mock_reference'
    ) AND NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'tuition_ledger_entries'
          AND column_name = 'billing_reference'
    ) THEN
        ALTER TABLE tuition_ledger_entries RENAME COLUMN mock_reference TO billing_reference;
    END IF;
END $$;

ALTER TABLE tuition_ledger_entries
    ADD CONSTRAINT chk_tuition_ledger_status
        CHECK (status IN ('PENDING', 'PAID', 'CANCELLED'));

CREATE TABLE IF NOT EXISTS billing_accounts (
    id               BIGSERIAL PRIMARY KEY,
    guardian_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    display_name     VARCHAR(200) NOT NULL,
    status           VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at       TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMP NOT NULL DEFAULT NOW(),
    version          BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_billing_account_guardian UNIQUE (guardian_user_id),
    CONSTRAINT chk_billing_account_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE IF NOT EXISTS billing_profiles (
    id                        BIGSERIAL PRIMARY KEY,
    account_id                BIGINT NOT NULL REFERENCES billing_accounts(id) ON DELETE RESTRICT,
    receiver_name             VARCHAR(200) NOT NULL,
    receiver_address          VARCHAR(300),
    receiver_document_type    INT,
    receiver_document_number  VARCHAR(20),
    receiver_vat_condition_id INT,
    default_voucher_type      INT,
    default_fiscal_concept    INT NOT NULL DEFAULT 2,
    fiscal_currency           VARCHAR(3) NOT NULL DEFAULT 'PES',
    rg_5866_applicable        BOOLEAN NOT NULL DEFAULT FALSE,
    status                    VARCHAR(20) NOT NULL DEFAULT 'INCOMPLETE',
    updated_by                BIGINT REFERENCES users(id) ON DELETE RESTRICT,
    created_at                TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at                TIMESTAMP NOT NULL DEFAULT NOW(),
    version                   BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_billing_profile_account UNIQUE (account_id),
    CONSTRAINT chk_billing_profile_status CHECK (status IN ('INCOMPLETE', 'READY')),
    CONSTRAINT chk_billing_profile_concept CHECK (default_fiscal_concept BETWEEN 1 AND 3),
    CONSTRAINT chk_billing_profile_rg5866_first_client CHECK (rg_5866_applicable = FALSE)
);

CREATE TABLE IF NOT EXISTS billing_charges (
    id             BIGSERIAL PRIMARY KEY,
    account_id     BIGINT NOT NULL REFERENCES billing_accounts(id) ON DELETE RESTRICT,
    student_id     BIGINT REFERENCES students(id) ON DELETE RESTRICT,
    student_name   VARCHAR(200) NOT NULL,
    source_type    VARCHAR(40) NOT NULL,
    source_id      BIGINT NOT NULL,
    concept        VARCHAR(80) NOT NULL,
    description    VARCHAR(500) NOT NULL,
    amount         NUMERIC(12, 2) NOT NULL,
    currency       VARCHAR(3) NOT NULL DEFAULT 'ARS',
    due_date       DATE NOT NULL,
    service_from   DATE,
    service_to     DATE,
    status         VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    paid_at        TIMESTAMP,
    created_at     TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMP NOT NULL DEFAULT NOW(),
    version        BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_billing_charge_source UNIQUE (source_type, source_id),
    CONSTRAINT chk_billing_charge_amount CHECK (amount >= 0),
    CONSTRAINT chk_billing_charge_status CHECK (status IN ('OPEN', 'PAID', 'CANCELLED'))
);

CREATE INDEX IF NOT EXISTS idx_billing_charge_status_due
    ON billing_charges(status, due_date);
CREATE INDEX IF NOT EXISTS idx_billing_charge_student
    ON billing_charges(student_id);
CREATE INDEX IF NOT EXISTS idx_billing_charge_account
    ON billing_charges(account_id);

CREATE TABLE IF NOT EXISTS payment_allocations (
    id         BIGSERIAL PRIMARY KEY,
    payment_id BIGINT NOT NULL REFERENCES payments(id) ON DELETE RESTRICT,
    charge_id  BIGINT NOT NULL REFERENCES billing_charges(id) ON DELETE RESTRICT,
    amount     NUMERIC(12, 2) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_payment_allocation_charge UNIQUE (charge_id),
    CONSTRAINT chk_payment_allocation_amount CHECK (amount > 0)
);

CREATE INDEX IF NOT EXISTS idx_payment_allocation_payment
    ON payment_allocations(payment_id);

ALTER TABLE fiscal_invoices
    ADD COLUMN IF NOT EXISTS charge_id BIGINT REFERENCES billing_charges(id) ON DELETE RESTRICT;

ALTER TABLE fiscal_invoices
    ALTER COLUMN payment_id DROP NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uk_fiscal_invoice_charge
    ON fiscal_invoices(charge_id)
    WHERE charge_id IS NOT NULL;

ALTER TABLE fiscal_invoices
    DROP CONSTRAINT IF EXISTS chk_fiscal_invoice_source;

ALTER TABLE fiscal_invoices
    ADD CONSTRAINT chk_fiscal_invoice_source
        CHECK (
            (payment_id IS NOT NULL AND charge_id IS NULL)
            OR (payment_id IS NULL AND charge_id IS NOT NULL)
        );

CREATE TABLE IF NOT EXISTS billing_runs (
    id               BIGSERIAL PRIMARY KEY,
    idempotency_key  VARCHAR(128) NOT NULL,
    request_fingerprint VARCHAR(64) NOT NULL,
    selection_mode   VARCHAR(20) NOT NULL,
    amount_treatment VARCHAR(20) NOT NULL,
    requested_by     BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    issue_date       DATE NOT NULL,
    selected_count   INT NOT NULL,
    created_count    INT NOT NULL,
    status           VARCHAR(20) NOT NULL DEFAULT 'COMPLETED',
    created_at       TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_billing_run_key UNIQUE (idempotency_key),
    CONSTRAINT chk_billing_run_selection CHECK (selection_mode IN ('INDIVIDUAL', 'SELECTED', 'FILTERED')),
    CONSTRAINT chk_billing_run_treatment CHECK (amount_treatment IN ('NON_TAXED', 'EXEMPT')),
    CONSTRAINT chk_billing_run_status CHECK (status IN ('COMPLETED')),
    CONSTRAINT chk_billing_run_counts CHECK (
        selected_count >= 0 AND created_count >= 0 AND created_count <= selected_count
    )
);

CREATE TABLE IF NOT EXISTS billing_run_items (
    id         BIGSERIAL PRIMARY KEY,
    run_id     BIGINT NOT NULL REFERENCES billing_runs(id) ON DELETE RESTRICT,
    charge_id  BIGINT NOT NULL REFERENCES billing_charges(id) ON DELETE RESTRICT,
    invoice_id BIGINT NOT NULL REFERENCES fiscal_invoices(id) ON DELETE RESTRICT,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_billing_run_charge UNIQUE (run_id, charge_id),
    CONSTRAINT uk_billing_run_invoice UNIQUE (invoice_id)
);
