-- =============================================================================
-- V1__create_courses_module.sql
-- Documents the current courses bounded context schema.
-- =============================================================================

CREATE TABLE IF NOT EXISTS courses (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR(255) NOT NULL UNIQUE,
    name          VARCHAR(255) NOT NULL,
    description   VARCHAR(1000) NOT NULL,
    level         VARCHAR(255) NOT NULL,
    duration      INT NOT NULL,
    max_students  INT NOT NULL,
    min_students  INT NOT NULL,
    teacher_id    BIGINT NOT NULL,
    price         NUMERIC(10, 2) NOT NULL,
    start_date    DATE,
    end_date      DATE,
    status        VARCHAR(255) NOT NULL,
    is_published  BOOLEAN NOT NULL,
    created_at    TIMESTAMP NOT NULL,
    updated_at    TIMESTAMP NOT NULL,
    CONSTRAINT courses_level_check CHECK (
        level IN (
            'BEGINNER',
            'ELEMENTARY',
            'PRE_INTERMEDIATE',
            'INTERMEDIATE',
            'UPPER_INTERMEDIATE',
            'ADVANCED',
            'PROFICIENCY'
        )
    ),
    CONSTRAINT courses_status_check CHECK (
        status IN ('ACTIVE', 'INACTIVE', 'COMPLETED', 'CANCELLED')
    )
);

CREATE TABLE IF NOT EXISTS enrollments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id      BIGINT NOT NULL,
    course_id       BIGINT NOT NULL REFERENCES courses(id),
    enrollment_date DATE NOT NULL,
    status          VARCHAR(255) NOT NULL,
    final_grade     NUMERIC(5, 2),
    completion_date DATE,
    notes           VARCHAR(1000),
    created_at      TIMESTAMP NOT NULL,
    updated_at      TIMESTAMP NOT NULL,
    CONSTRAINT enrollments_status_check CHECK (
        status IN ('ACTIVE', 'COMPLETED', 'FAILED', 'DROPPED', 'SUSPENDED')
    )
);

CREATE TABLE IF NOT EXISTS course_attendance (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id   BIGINT NOT NULL REFERENCES enrollments(id),
    attendance_date DATE NOT NULL,
    status          VARCHAR(255) NOT NULL,
    notes           VARCHAR(500),
    recorded_by     BIGINT NOT NULL,
    created_at      TIMESTAMP NOT NULL,
    updated_at      TIMESTAMP NOT NULL,
    CONSTRAINT course_attendance_status_check CHECK (
        status IN ('PRESENT', 'ABSENT', 'LATE', 'EXCUSED_ABSENCE', 'SICK_LEAVE')
    )
);

CREATE INDEX IF NOT EXISTS idx_attendance_enrollment ON course_attendance(enrollment_id);
CREATE INDEX IF NOT EXISTS idx_attendance_date ON course_attendance(attendance_date);

CREATE TABLE IF NOT EXISTS course_materials (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id   BIGINT NOT NULL REFERENCES courses(id),
    title       VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    type        VARCHAR(255) NOT NULL,
    file_url    VARCHAR(255) NOT NULL,
    file_name   VARCHAR(255),
    file_size   BIGINT,
    mime_type   VARCHAR(255),
    uploaded_by BIGINT NOT NULL,
    is_visible  BOOLEAN NOT NULL,
    order_index INT,
    created_at  TIMESTAMP NOT NULL,
    updated_at  TIMESTAMP NOT NULL,
    CONSTRAINT course_materials_type_check CHECK (
        type IN ('PDF', 'VIDEO', 'AUDIO', 'IMAGE', 'DOCUMENT', 'PRESENTATION', 'LINK', 'ZIP', 'OTHER')
    )
);

CREATE TABLE IF NOT EXISTS course_certificates (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id     BIGINT NOT NULL UNIQUE REFERENCES enrollments(id),
    certificate_code  VARCHAR(255) NOT NULL UNIQUE,
    issue_date        DATE NOT NULL,
    expiry_date       DATE,
    final_grade       NUMERIC(5, 2) NOT NULL,
    honors            VARCHAR(500),
    notes             VARCHAR(1000),
    pdf_url           VARCHAR(255),
    status            VARCHAR(255) NOT NULL,
    issued_by         BIGINT NOT NULL,
    revoked_by        BIGINT,
    revoked_at        TIMESTAMP,
    revocation_reason VARCHAR(500),
    created_at        TIMESTAMP NOT NULL,
    updated_at        TIMESTAMP NOT NULL,
    CONSTRAINT course_certificates_status_check CHECK (
        status IN ('ACTIVE', 'REVOKED', 'EXPIRED')
    )
);

CREATE INDEX IF NOT EXISTS idx_certificate_enrollment ON course_certificates(enrollment_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_certificate_code ON course_certificates(certificate_code);
