-- =============================================================================
-- V2__create_sessions_module.sql
-- Documents the current course sessions and session exceptions schema.
-- =============================================================================

CREATE TABLE IF NOT EXISTS course_sessions (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id         BIGINT NOT NULL REFERENCES courses(id),
    session_date      DATE NOT NULL,
    start_time        TIME NOT NULL,
    end_time          TIME NOT NULL,
    classroom_id      BIGINT,
    classroom_name    VARCHAR(255),
    status            VARCHAR(255) NOT NULL,
    topic             VARCHAR(1000),
    notes             VARCHAR(1000),
    is_recurring      BOOLEAN NOT NULL,
    recurrence_rule   VARCHAR(255),
    parent_session_id BIGINT,
    created_at        TIMESTAMP NOT NULL,
    updated_at        TIMESTAMP NOT NULL,
    CONSTRAINT course_sessions_status_check CHECK (
        status IN ('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'RESCHEDULED')
    )
);

CREATE INDEX IF NOT EXISTS idx_session_course ON course_sessions(course_id);
CREATE INDEX IF NOT EXISTS idx_session_date ON course_sessions(session_date);
CREATE INDEX IF NOT EXISTS idx_session_classroom ON course_sessions(classroom_id);

CREATE TABLE IF NOT EXISTS session_exceptions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id       BIGINT NOT NULL REFERENCES course_sessions(id),
    exception_date   DATE NOT NULL,
    exception_type   VARCHAR(255) NOT NULL,
    new_start_time   TIME,
    new_end_time     TIME,
    new_classroom_id BIGINT,
    reason           VARCHAR(500),
    created_at       TIMESTAMP NOT NULL,
    CONSTRAINT session_exceptions_exception_type_check CHECK (
        exception_type IN ('CANCELLED', 'RESCHEDULED', 'HOLIDAY', 'CLASSROOM_CHANGE')
    )
);

CREATE INDEX IF NOT EXISTS idx_exception_session ON session_exceptions(session_id);
CREATE INDEX IF NOT EXISTS idx_exception_date ON session_exceptions(exception_date);
