-- V36 - Support multiple academic guardians per student while preserving guardian_id
-- as the optional primary compatibility pointer.
-- Manual PostgreSQL migration. Re-runnable and safe for ddl-auto=validate.

BEGIN;

CREATE TABLE IF NOT EXISTS student_guardian_relationships (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id bigint NOT NULL,
    guardian_user_id bigint NOT NULL,
    relationship_type varchar(32),
    is_primary boolean NOT NULL DEFAULT false,
    can_view_academic boolean NOT NULL DEFAULT true,
    is_billing_contact boolean NOT NULL DEFAULT false,
    active boolean NOT NULL DEFAULT true,
    source_system varchar(80) NOT NULL DEFAULT 'APPLICATION',
    source_reference varchar(255),
    reconciliation_run_id varchar(64),
    verified_by bigint,
    verified_at timestamp,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now(),
    version bigint NOT NULL DEFAULT 0,
    CONSTRAINT uq_student_guardian_relationship UNIQUE (student_id, guardian_user_id),
    CONSTRAINT chk_student_guardian_relationship_type CHECK (
        relationship_type IS NULL OR relationship_type IN (
            'MADRE', 'PADRE', 'TUTOR/A', 'AUTOTUTELA', 'ABUELA', 'ABUELO', 'OTRO'
        )
    )
);

-- The reconciliation import originally required a run id. Relationships created
-- later through the application are independent from a legacy reconciliation run.
ALTER TABLE student_guardian_relationships
    ALTER COLUMN reconciliation_run_id DROP NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_student_guardian_student') THEN
        ALTER TABLE student_guardian_relationships
            ADD CONSTRAINT fk_student_guardian_student
            FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE NOT VALID;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_student_guardian_user') THEN
        ALTER TABLE student_guardian_relationships
            ADD CONSTRAINT fk_student_guardian_user
            FOREIGN KEY (guardian_user_id) REFERENCES users(id) ON DELETE RESTRICT NOT VALID;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_student_guardian_reconciliation_run') THEN
        ALTER TABLE student_guardian_relationships
            ADD CONSTRAINT fk_student_guardian_reconciliation_run
            FOREIGN KEY (reconciliation_run_id) REFERENCES legacy_reconciliation_runs(run_id)
            ON DELETE RESTRICT NOT VALID;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_student_guardian_verified_by') THEN
        ALTER TABLE student_guardian_relationships
            ADD CONSTRAINT fk_student_guardian_verified_by
            FOREIGN KEY (verified_by) REFERENCES users(id) ON DELETE RESTRICT NOT VALID;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_student_guardian_relationship_student
    ON student_guardian_relationships(student_id, active);
CREATE INDEX IF NOT EXISTS idx_student_guardian_relationship_guardian
    ON student_guardian_relationships(guardian_user_id, active, can_view_academic);
CREATE INDEX IF NOT EXISTS idx_student_guardian_relationship_billing
    ON student_guardian_relationships(guardian_user_id, active, is_billing_contact);
CREATE UNIQUE INDEX IF NOT EXISTS uq_student_guardian_primary_active
    ON student_guardian_relationships(student_id)
    WHERE active AND is_primary;

-- Preserve every legacy scalar association as an active primary relationship.
UPDATE student_guardian_relationships sgr
SET is_primary = false,
    updated_at = now()
FROM students s
WHERE s.id = sgr.student_id
  AND s.guardian_id IS NOT NULL
  AND sgr.guardian_user_id <> s.guardian_id
  AND sgr.active
  AND sgr.is_primary;

INSERT INTO student_guardian_relationships (
    student_id,
    guardian_user_id,
    is_primary,
    can_view_academic,
    active,
    source_system,
    source_reference,
    created_at,
    updated_at,
    version
)
SELECT
    s.id,
    s.guardian_id,
    true,
    true,
    true,
    'LEGACY_SCALAR_BACKFILL',
    'students.guardian_id',
    now(),
    now(),
    0
FROM students s
WHERE s.guardian_id IS NOT NULL
ON CONFLICT (student_id, guardian_user_id) DO UPDATE
SET is_primary = true,
    can_view_academic = true,
    active = true,
    updated_at = now();

ALTER TABLE student_guardian_relationships VALIDATE CONSTRAINT fk_student_guardian_student;
ALTER TABLE student_guardian_relationships VALIDATE CONSTRAINT fk_student_guardian_user;
ALTER TABLE student_guardian_relationships VALIDATE CONSTRAINT fk_student_guardian_reconciliation_run;
ALTER TABLE student_guardian_relationships VALIDATE CONSTRAINT fk_student_guardian_verified_by;

COMMIT;
