-- =============================================================================
-- V3__create_security_students_module.sql
-- Documents the current users and students schema generated by the application.
-- =============================================================================

CREATE TABLE IF NOT EXISTS users (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username          VARCHAR(255) NOT NULL UNIQUE,
    email             VARCHAR(255) NOT NULL UNIQUE,
    password          VARCHAR(255) NOT NULL,
    first_name        VARCHAR(255) NOT NULL,
    last_name         VARCHAR(255) NOT NULL,
    role              VARCHAR(255) NOT NULL,
    status            VARCHAR(255) NOT NULL,
    active            BOOLEAN NOT NULL,
    phone_number      VARCHAR(255),
    address           VARCHAR(255),
    date_of_birth     DATE,
    document_number   VARCHAR(255),
    emergency_contact VARCHAR(255),
    created_at        TIMESTAMP NOT NULL,
    updated_at        TIMESTAMP NOT NULL,
    CONSTRAINT users_role_check CHECK (role IN ('ADMIN', 'TEACHER', 'GUARDIAN')),
    CONSTRAINT users_status_check CHECK (status IN ('PENDING_APPROVAL', 'ACTIVE', 'REJECTED'))
);

CREATE TABLE IF NOT EXISTS students (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name        VARCHAR(255) NOT NULL,
    last_name         VARCHAR(255) NOT NULL,
    email             VARCHAR(255) NOT NULL UNIQUE,
    phone_number      VARCHAR(255) NOT NULL,
    date_of_birth     DATE NOT NULL,
    address           VARCHAR(255) NOT NULL,
    guardian_id       BIGINT,
    document_number   VARCHAR(255) NOT NULL,
    emergency_contact VARCHAR(255) NOT NULL,
    active            BOOLEAN NOT NULL,
    current_level     VARCHAR(255) NOT NULL,
    enrollment_date   DATE NOT NULL,
    medical_notes     VARCHAR(1000),
    photo_url         VARCHAR(500),
    created_at        TIMESTAMP NOT NULL,
    updated_at        TIMESTAMP NOT NULL
);
