-- =============================================================================
-- V4__create_staff_module.sql
-- Documents the current teaching, non-teaching and staff attendance schema.
-- =============================================================================

CREATE TABLE IF NOT EXISTS teaching_staff (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at                 TIMESTAMP NOT NULL,
    created_by                 VARCHAR(255) NOT NULL,
    is_active                  BOOLEAN,
    updated_at                 TIMESTAMP,
    updated_by                 VARCHAR(255),
    first_name                 VARCHAR(255) NOT NULL,
    last_name                  VARCHAR(255) NOT NULL,
    email                      VARCHAR(255) NOT NULL UNIQUE,
    phone_number               VARCHAR(255) NOT NULL,
    document_number            VARCHAR(255) NOT NULL UNIQUE,
    birth_date                 DATE NOT NULL,
    address                    VARCHAR(255) NOT NULL,
    emergency_contact_name     VARCHAR(255) NOT NULL,
    emergency_contact_phone    VARCHAR(255) NOT NULL,
    hire_date                  DATE NOT NULL,
    monthly_salary             DOUBLE PRECISION NOT NULL,
    payment_status             VARCHAR(255) NOT NULL,
    assigned_students_count    INT NOT NULL,
    specialization             TEXT,
    qualifications             TEXT,
    notes                      TEXT,
    observations               TEXT,
    CONSTRAINT teaching_staff_payment_status_check CHECK (
        payment_status IN ('UP_TO_DATE', 'PENDING', 'OVERDUE', 'PARTIALLY_PAID')
    )
);

CREATE TABLE IF NOT EXISTS non_teaching_staff (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at                 TIMESTAMP NOT NULL,
    created_by                 VARCHAR(255) NOT NULL,
    is_active                  BOOLEAN,
    updated_at                 TIMESTAMP,
    updated_by                 VARCHAR(255),
    first_name                 VARCHAR(255) NOT NULL,
    last_name                  VARCHAR(255) NOT NULL,
    email                      VARCHAR(255) NOT NULL UNIQUE,
    phone_number               VARCHAR(255) NOT NULL,
    document_number            VARCHAR(255) NOT NULL UNIQUE,
    birth_date                 DATE NOT NULL,
    address                    VARCHAR(255) NOT NULL,
    emergency_contact_name     VARCHAR(255) NOT NULL,
    emergency_contact_phone    VARCHAR(255) NOT NULL,
    hire_date                  DATE NOT NULL,
    hourly_rate                DOUBLE PRECISION NOT NULL,
    role                       VARCHAR(255),
    assigned_tasks             TEXT,
    company_name               VARCHAR(255),
    observations               TEXT,
    CONSTRAINT non_teaching_staff_role_check CHECK (
        role IN ('CLEANING', 'MAINTENANCE', 'IT_SUPPORT', 'IT', 'SECURITY', 'ADMINISTRATION', 'OTHER')
    )
);

CREATE TABLE IF NOT EXISTS staff_attendance (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attendance_date       DATE NOT NULL,
    check_in_time         TIME,
    check_out_time        TIME,
    hours_worked          DOUBLE PRECISION,
    status                VARCHAR(255) NOT NULL,
    notes                 TEXT,
    teaching_staff_id     BIGINT REFERENCES teaching_staff(id),
    non_teaching_staff_id BIGINT REFERENCES non_teaching_staff(id),
    CONSTRAINT staff_attendance_status_check CHECK (
        status IN ('PRESENT', 'ABSENT', 'LATE', 'EXCUSED', 'SICK_LEAVE', 'VACATION')
    )
);

CREATE INDEX IF NOT EXISTS idx_teaching_staff_id ON staff_attendance(teaching_staff_id);
CREATE INDEX IF NOT EXISTS idx_non_teaching_staff_id ON staff_attendance(non_teaching_staff_id);
