\set ON_ERROR_STOP on

REVOKE ALL ON DATABASE sigep_prod FROM PUBLIC;
REVOKE ALL ON DATABASE sigep_prod FROM sigep_app_prod;
GRANT CONNECT ON DATABASE sigep_prod TO sigep_app_prod;

REVOKE CREATE ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM sigep_app_prod;
GRANT USAGE ON SCHEMA public TO sigep_app_prod;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA public
TO sigep_app_prod;

GRANT USAGE, SELECT, UPDATE
ON ALL SEQUENCES IN SCHEMA public
TO sigep_app_prod;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO sigep_app_prod;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO sigep_app_prod;
